### ISSUE TITLE
End Round Stats panel's tabs don't change colour correctly

### ISSUE THREAD

**Issue by PiTM0N** [punyhumangames/Dystopia#13]
**Steps to reproduce**:

1. Have the End Round stat panel open
2. Click on the tab of your choice,
3. Click on another tab, previous tab didn't change its colour back.

So far 100% reproductable, regardless of team.  It seems to be that tabs **always** toggle their colour on click, but forgot to change back to the original state, when an other tab is clicked on.

Non-listed video showing the issue:
https://youtu.be/VUZU8_7MhdY

**Comment by Joshua-Ashton** [comment]
1.5.2 Fixed
