### ISSUE TITLE
Spawn effect missing

### ISSUE THREAD

**Issue by atomy** [punyhumangames/Dystopia#22]
When spawning there used to be a screen effect (shader?) and sound effect. The sound effect is still there, the screen effect is not. You just "plop" into the world. The spawn direction seems to be also random and not aligned to spawn pad.

**Comment by urinal-cake** [comment]
Still missing most of its effect and sound

**Comment by atomy** [comment]
Video of old dys right before spawn: https://youtu.be/pYLYiO-7-48?t=112

**Comment by Joshua-Ashton** [comment]
Fixed next update.
