### ISSUE TITLE
Bloom effect when creating an ICE Barrier

### ISSUE THREAD

**Issue by Quantx** [punyhumangames/Dystopia#3]
![bloom effect](https://user-images.githubusercontent.com/2834674/36225291-31cd2d04-1198-11e8-9df5-31fb19cb3cb1.jpg)
As you can see, the text is pretty unreadable. This bloom effect does not occur with any other programs. I had bloom turned off in the graphic options when I took this screenshot.

**Comment by Joshua-Ashton** [comment]
1.5.2 fixed
