### ISSUE TITLE
Headshot kills causes a texture glitch

### ISSUE THREAD

**Issue by psychodewon** [punyhumangames/Dystopia#33]
how to reproduce : kill a corps/punk that is medium/light with a headshot with a weapon such as mk rifle, laser rifle...
it last about half a second
maybe the headgibs is related, dunno

headshot incoming:
![top10momentstakenbeforedisaster](https://user-images.githubusercontent.com/36637073/36389447-633ede2c-159f-11e8-87b7-be52068dd4cb.png)

headshot glitch in action:
![headshotglitch](https://user-images.githubusercontent.com/36637073/36389468-6d289162-159f-11e8-9e3b-6567015af353.png)

edit:
prelly sure it's the falling blood effect expanding

**Comment by urinal-cake** [comment]
Thank you for getting screenshots of this! It would have taken me forever.
This also occurs when a cortex goes off.

**Comment by urinal-cake** [comment]
This was addressed with 1.5.3.
