### ISSUE TITLE
Unable to import Targa files for sprays

### ISSUE THREAD

**Issue by PiTM0N** [punyhumangames/Dystopia#37]
There seems to be an issue with importing custom .tga sprays. When attempting to, **you'll run into the following error**, stating:  "Unable to load vtax_dll.dll Try restarting steam to get the latest updates.
Picture or error prompt:
https://media.discordapp.net/attachments/314078504558002176/415275774061445121/unknown.png

**Things that did not fix the issue for me:**

- Restarting steam, to get the latest updates,
- Verifying GCFs,
- Moving the file to "common\Dystopia\dystopia\materials\vgui\logos".

I've attached the picture I was trying to import in a .zip archive, open at your own risk. Also, the latest build of Team Fortress 2 could import this file, and use it ingame, if that is any useful information. 

**EDIT:** I have not tried any other supported image or texture format.
[PiTM0N_tga_spray.zip](https://github.com/punyhumangames/Dystopia/files/1738538/PiTM0N_tga_spray.zip)

**Comment by Joshua-Ashton** [comment]
Fixed in next update.
