### ISSUE TITLE
Minor update broke the game again :(

### ISSUE THREAD

**Issue by adriencarbonne** [punyhumangames/Dystopia#4]
Hello, yesterday everything was fine, but right now Steam updated Dystopia once again and since this update I can only see one US server.

I cannot join existing EU servers because "server is using an older version of the game" :(

Help ?!!

**Comment by adriencarbonne** [comment]
OK, urinal-cake just published the 1.5.1 news on Steam, so I guess I just have to wait for others to update :)

Thank you very much for your hard work on Dystopia!!!! <3

**Comment by urinal-cake** [comment]
Sorry about that adrien! We're working hard to patch the patch, fixing fixes and re-compiling recompiles.
