### ISSUE TITLE
Sprays do not show on JIPs after getting kicked out of cyberspace

### ISSUE THREAD

**Issue by PiTM0N** [punyhumangames/Dystopia#40]
When someone kicks your butt from cyberspace, the JIP you were occupying either shows the cyber-spawn area, or just blank black. I belive it used to show the killer's spray on your JIP.

**Steps to reproduce:**

1. Get into cyber,
2. Have someone spank you there very hard,
3. Now your JIP should be should be either black, or 'normal', instead of showing a spray.

So far 100% reproductable, regardles of your chosen Team or map. 
Non-listed short video demonstrating the issue:
https://youtu.be/IkUw-1Kl49Y

I've attached a picture showing the black screen alternative.
![20180220170201_1](https://user-images.githubusercontent.com/36541127/36480602-30ad1180-170d-11e8-8630-b709abc0e9d6.jpg)

**Comment by Joshua-Ashton** [comment]
Fixed in next update
