### ISSUE TITLE
`say` message is dropped if typing when end-of-game occurs

### ISSUE THREAD

**Issue by Cokemonkey11** [punyhumangames/Dystopia#46]
1. start typing a `say` message
2. game timer runs out (corps (usually) win)
3. your say box disappears and your message is dropped

expected behavior: say box is still up and end-of-game dialogs UIs still appear as well.

**Comment by urinal-cake** [comment]
This should have been fixed in 1.5.2, I can  not reproduce it on 1.5.4 release candidate.
