### ISSUE TITLE
"Weapon" and "Implants" tabs are not selectable from loadout screen

### ISSUE THREAD

**Issue by wealthysoup** [punyhumangames/Dystopia#47]
When you have an existing loadout (even if you don't - but much less important) and attempt to change it (from the 'm' menu) you need to reselect class and then weapon and then loadout.

The "Weapon" and "Implants" tabs at the top of the loadout screen can't be selected. This means that to change an implant you must first click thje "Class" tab, confirm your class and reselect your weapon before being able to change an implant.

**Comment by Joshua-Ashton** [comment]
Fixed in next update.
