### ISSUE TITLE
Spawning after spectating causes view to tilt/roll

### ISSUE THREAD

**Issue by urinal-cake** [punyhumangames/Dystopia#5]
1. Die in a match with multiple players
2. Rinse and repeat until your death camera attaches to a ragdoll and the view tilts
3. Right before respawn, switch spectator camera to someone in cyberspace
4. Spawn
5. Tilted/rolled camera.

Not exact repro, there's a soft mix of these steps to recreate.

**Comment by Joshua-Ashton** [comment]
1.5.2 needs testing

**Comment by Cokemonkey11** [comment]
Looks fixed in live stable.

**Comment by urinal-cake** [comment]
Duplicate of #1
