### ISSUE TITLE
Spawn Effect's toggle is broken

### ISSUE THREAD

**Issue by PiTM0N** [punyhumangames/Dystopia#55]
The toggle under multiplayer options -> advanced makes no change related to spawn effect. Now, **wether it is on or off, you'll get the audio fade-in for all channels (_even for voice chat!!!_), and you won't get the visual fade in effect.** I belive you could turn it off in the past, but even if it was on, it didn't apply the audio fade-in to voice chat.

Short video of the toggle not doing anything (I know, very intersting):
https://youtu.be/Bvw6zU21wx4

**Comment by Joshua-Ashton** [comment]
Fixed next update.
