### ISSUE TITLE
Team chat and voicecomms is not colored correctly

### ISSUE THREAD

**Issue by urinal-cake** [punyhumangames/Dystopia#7]
Dystopia 1.4 (intended behavior)
Global chat:
The player's name would be colored red or blue depending on their team. The player's text would be colored orange (let's keep it gray, though.)

Team chat:
The player's name would be colored red or blue, depending on their team. The player's text would also be colored red or blue depending on their team.

At the moment, team chat shows as gray for both the player's name and the player's text.
The same can be said of voice comms.

**Comment by Joshua-Ashton** [comment]
1.5.2 fixed
